Repository BC-MAR-21-ROR/kata-07-rejoj-checador-equipo-03-k07, pull requests merged in 2021-05, with the labels that each got.

#30 Feature#19 disabling employees
  Gemfile
  Gemfile.lock
  app/controllers/employees_controller.rb
  app/views/employees/_form.html.erb
  app/views/employees/index.html.erb
  app/views/employees/show.html.erb
  app/views/employees/toggle_enabled_status.js.erb
  config/routes.rb
Labels: high priority

#35 Feature#15 generate report
  Gemfile
  Gemfile.lock
  app/controllers/reports_controller.rb
  app/javascript/packs/application.js
  app/javascript/packs/eventChangeDate.js
  app/javascript/packs/navtabs.js
  app/javascript/src/bootstrap.js
  app/models/log.rb
  app/views/layouts/_input_date.html.erb
  app/views/layouts/_navbar.html.erb
  app/views/layouts/_navtabs.html.erb
  app/views/reports/index.html.erb
  app/views/reports/show.xlsx.axlsx
  config/routes.rb
Labels: high priority, review required

#36 Feature#32 final makeup for stylesheets
  Gemfile.lock
  app/assets/images/logo-bc.png
  app/assets/images/sign_out.svg
  app/controllers/company_branches_controller.rb
  app/controllers/employees_controller.rb
  app/javascript/packs/_custom.scss
  app/javascript/packs/application.js
  app/javascript/packs/application.scss
  app/javascript/src/bootstrap.js
  app/views/company_branches/index.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/employees/_form.html.erb
  app/views/employees/index.html.erb
  app/views/employees/toggle_enabled_status.js.erb
  app/views/layouts/_navbar.html.erb
  app/views/layouts/application.html.erb
  app/views/logs/new.html.erb
  package.json
  yarn.lock
Labels: nice to have
